language: go
sudo: false
notifications:
  email: false
go:
- 1.11
- tip
os:
- linux
- osx
env:
- GO111MODULE=on
matrix:
  allow_failures:
  - go: tip
  fast_finish: true
install:
- go get golang.org/x/lint/golint
- go get github.com/mattn/goveralls
script:
- go fmt ./...
- go vet ./...
- golint ./...
- go test -timeout 15s -race ./...
- go test -timeout 15s -cover -covermode=atomic -coverprofile=coverage.out ./...
- goveralls -coverprofile=coverage.out -service=travis-ci
- go build -race
